---
# defaults file for certbot

# Certbot auto-renew cron job configuration (for certificate renewals).
certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--quiet --no-self-upgrade"

# Parameters used when creating new Certbot certs.
certbot_create_if_missing: false
certbot_create_method: nginx
certbot_admin_email: segun@darey.io


certbot_certs: 
- email: segun@darey.io
  domains:
    - livingstone.cf
#     - example2.com
# - domains:
#     - example3.com


certbot_create_command: >-
  certbot  --nginx --noninteractive --agree-tos --email segun@darey.io -d livingstone.cf

