pipeline{
   agent any

   environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
   }

     parameters {
      string(name: 'inventory_file', defaultValue: 'inventory/dev',  description: 'A variable to select the enviroment to run the job')
      string(name: 'ansible_tag', defaultValue: '',  description: 'This is the tag to decide what role or playbook to run')
    }
     

   stages{

      stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }

      stage('Checkout SCM') {
         steps{
            git branch: 'feature/project-14', url: 'https://github.com/Livingstone95/ansible-config-mg.git'
         }
       }
      stage('Prepare Ansible For Execution') {
        steps {
          sh 'echo ${WORKSPACE}'
          sh 'sed -i \'s/roles_path = \\/var\\/lib\\/jenkins\\/workspace/roles_path = \\/var\\/lib\\/jenkins\\/workspace\\/ansible-project_release-0.0.1\\/roles /g\' deploy/ansible.cfg'
        }
      }

      stage('Run Ansible') {
        steps {
              ansiblePlaybook colorized: true, credentialsId: 'ansadmin2', disableHostKeyChecking: true, installation: 'Ansible', inventory: 'inventory/dev', playbook: 'playbooks/site.yml'   
                  }
      }

      stage('Clean Workspace after build'){
        steps{
          cleanWs()
        }
      }
   }
}   