 pipeline {
    agent any


  stages {
    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }


    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }
    
    stage('Test2') {
      steps {
        script {
          sh 'echo "Testing Stage Number Two"'
        }
      }
    }

    stage('Package') {
      steps {
        script {
          sh 'echo "packaging Stage"'
        }
      }
    }

    stage('Deploy') {
      steps {
        script {
          sh 'echo "Deploy to production"'
        }
      }
    }

    }
}