---
# tasks file for mysql

- name: install mysql 
  ansible.builtin.yum:
    name: mysql-server
    state: present

- name: ensure mysql is started and enabled
  ansible.builtin.service:
     name: mysqld
     state: started 
     enabled: yes

- name: create /var/lib/mysql/mysql.sock
  ansible.builtin.file:
    path: /var/lib/mysql/mysql.sock
    state: touch

- name: create database
  community.mysql.mysql_db:
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: create user
  community.mysql.mysql_user:
    name: tooling
    host: '0.0.0.0'
    password: tooling
    priv: '*.*:ALL,GRANT'
    state: present


# - name: update /ect/my.cf for bind-address
#   ansible.builtin.template:
#     src: templates/my.cnf.j2
#     dest: /etc/my.cnf
#   notify: Restart mysql


- import_tasks: configure-firewall.yml

