---
# tasks file for webservers
- name: install httpd on the webserver
  ansible.builtin.yum:
      name: "httpd"
      state: present


- name: ensure httpd is started and enabled
  ansible.builtin.service:
     name: httpd 
     state: started 
     enabled: yes

- name: install repositories
  ansible.builtin.yum:
    name:
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
      - install dnf-utils http://rpms.remirepo.net/enterprise/remi-release-8.rpm 
    disable_gpg_check: yes
    state: present

- name: install PHP
  ansible.builtin.yum:
    enablerepo: epel
    name:
      - php 
      - php-mysqlnd
      - php-opcache
      - php-gd 
      - php-curl
    state: present

- name: allow selinux to use httpd
  command: setsebool -P httpd_execmem 1

- name: ensure php-fpm is started and enabled
  ansible.builtin.service:
     name: php-fpm
     state: reloaded
     enabled: yes
  notify: Restart httpd


- import_tasks: setup-site.yml

- import_tasks: configure-firewall.yml