---
# tasks file for jenkins
- name: install java 11
  ansible.builtin.yum:
    name: java-11-openjdk-devel
    state: present


- name: set up java enviroment 
  ansible.builtin.template:
    src: templates/java-home.j2
    dest: /etc/profile.d/java.sh

- name: import repository key from jenkins
  ansible.builtin.rpm_key:
    state: present
    key: http://pkg.jenkins.io/redhat-stable/jenkins.io.key


- name: add the repository key to repos list
  ansible.builtin.get_url:
    url:  http://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
    mode: 0755


- name: install jenkins
  ansible.builtin.yum:
    name: jenkins
    state: present

- name: start and enable jenkins
  ansible.builtin.service:
    name: jenkins
    state: started
    enabled: yes

- import_tasks: configure-firewall.yml

- name: This the Administrator password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword