---
# handlers file for mysql

- name: Restart mysql
  ansible.builtin.service:
    name: mysqld
    state: restarted

- name: restart firewall
  ansible.builtin.service:
    name: firewalld
    state: restarted