---

- hosts: all
  become: true
- name: Include dynamic variables
  import_playbook: ../static-assignments/common.yml

#   include_playbook: ../dynamic-assignments/env-vars.yml
#   tags:
#     - always


# - hosts: webservers
# - name: Webserver assignment
#   ansible.builtin.import_playbook: ../static-assignments/webservers.yml

- hosts: database
- name: database assignment
  ansible.builtin.import_playbook: ../static-assignments/database.yml


- hosts: nginx
- name: nginx assignment
  ansible.builtin.import_playbook: ../static-assignments/nginx.yml
  
# - hosts: loadbalancer
# - name: loadbalancer assignment
#   ansible.builtin.import_playbook: ../static-assignments/loadbalancer.yml
#   when: load_balancer_is_required

# - hosts: loadbalancer
# - name: certbot assignment
#   ansible.builtin.import_playbook: ../static-assignments/certbot.yml

# - hosts: jenkins
# - name: jenkins assignment
#   ansible.builtin.import_playbook: ../static-assignments/jenkins.yml


# - hosts: artifactory
# - name: artifactory assignment
#   ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

# - hosts: sonarqube
# - name: sonarqube assignment
#   ansible.builtin.import_playbook: ../static-assignments/sonarqube.yml

